import type { Anomaly } from "./github";

const GITHUB_API_BASE = "https://api.github.com";
const HISTORY_BRANCH = "cron-job-doctor-history";
const HISTORY_LIMIT = 50; // capped per workflow file, oldest entries dropped

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required environment variable: ${name}`);
  return value;
}

function authHeaders() {
  return {
    Authorization: `Bearer ${requireEnv("GITHUB_TOKEN")}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

function historyPath(workflowId: number): string {
  return `.cron-job-doctor/history/${workflowId}.md`;
}

export interface DiagnosisSnapshot {
  timestamp: string;
  runs_analyzed: number;
  failure_rate_pct: number;
  avg_duration_min: number;
  anomaly_types: string[];
}

/** Ensures the dedicated history branch exists, creating it from the repo's default branch if not. */
async function ensureHistoryBranch(owner: string, repo: string): Promise<void> {
  const check = await fetch(
    `${GITHUB_API_BASE}/repos/${owner}/${repo}/git/ref/heads/${HISTORY_BRANCH}`,
    { headers: authHeaders() }
  );
  if (check.ok) return; // branch already exists

  const repoInfo = await fetch(`${GITHUB_API_BASE}/repos/${owner}/${repo}`, {
    headers: authHeaders(),
  }).then((r) => r.json());
  const defaultBranch = repoInfo.default_branch || "main";

  const baseRef = await fetch(
    `${GITHUB_API_BASE}/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`,
    { headers: authHeaders() }
  ).then((r) => r.json());

  await fetch(`${GITHUB_API_BASE}/repos/${owner}/${repo}/git/refs`, {
    method: "POST",
    headers: { ...authHeaders(), "Content-Type": "application/json" },
    body: JSON.stringify({
      ref: `refs/heads/${HISTORY_BRANCH}`,
      sha: baseRef.object.sha,
    }),
  });
}

function renderMarkdown(workflowId: number, entries: DiagnosisSnapshot[]): string {
  return (
    `# Cron Job Doctor -- Diagnosis History\n\n` +
    `Workflow ID: ${workflowId}\n` +
    `Auto-generated by cron-job-doctor-mcp on every diagnosis. Do not edit by hand ` +
    `-- this file is parsed back as JSON, and hand edits may break parsing.\n\n` +
    "```json\n" +
    JSON.stringify(entries, null, 2) +
    "\n```\n"
  );
}

function parseMarkdown(content: string): DiagnosisSnapshot[] {
  const match = content.match(/```json\n([\s\S]*?)\n```/);
  if (!match) return [];
  try {
    return JSON.parse(match[1]);
  } catch {
    return []; // corrupted or hand-edited file -- fail safe rather than throw
  }
}

/** Reads the current history file, if it exists. Returns entries plus the file's sha (needed to update it). */
async function readHistoryFile(
  owner: string,
  repo: string,
  workflowId: number
): Promise<{ entries: DiagnosisSnapshot[]; sha: string | null }> {
  const res = await fetch(
    `${GITHUB_API_BASE}/repos/${owner}/${repo}/contents/${historyPath(workflowId)}?ref=${HISTORY_BRANCH}`,
    { headers: authHeaders() }
  );
  if (res.status === 404) return { entries: [], sha: null };
  if (!res.ok) throw new Error(`GitHub API error ${res.status} reading history: ${await res.text()}`);

  const data = await res.json();
  const content = Buffer.from(data.content, "base64").toString("utf8");
  return { entries: parseMarkdown(content), sha: data.sha };
}

/** Writes the history file, retrying once on a 409 sha-conflict (concurrent write). */
async function writeHistoryFile(
  owner: string,
  repo: string,
  workflowId: number,
  entries: DiagnosisSnapshot[],
  sha: string | null,
  attempt = 0
): Promise<void> {
  const content = renderMarkdown(workflowId, entries);
  const res = await fetch(
    `${GITHUB_API_BASE}/repos/${owner}/${repo}/contents/${historyPath(workflowId)}`,
    {
      method: "PUT",
      headers: { ...authHeaders(), "Content-Type": "application/json" },
      body: JSON.stringify({
        message: `Record diagnosis for workflow ${workflowId}`,
        content: Buffer.from(content, "utf8").toString("base64"),
        branch: HISTORY_BRANCH,
        ...(sha ? { sha } : {}),
      }),
    }
  );

  if (res.status === 409 && attempt === 0) {
    // Someone else wrote to this file between our read and write -- re-read
    // the current sha and retry once rather than failing outright.
    const fresh = await readHistoryFile(owner, repo, workflowId);
    await writeHistoryFile(owner, repo, workflowId, entries, fresh.sha, attempt + 1);
    return;
  }
  if (!res.ok) {
    throw new Error(`GitHub API error ${res.status} writing history: ${await res.text()}`);
  }
}

/**
 * Records one diagnosis as a point-in-time snapshot, committed to a
 * dedicated `cron-job-doctor-history` branch (not main) so this doesn't
 * clutter the repo's regular commit history. Called every time
 * diagnose_workflow or diagnose_workflow_widget runs.
 */
export async function recordDiagnosis(
  owner: string,
  repo: string,
  workflowId: number,
  stats: { runs_analyzed: number; failure_rate_pct: number; avg_duration_min: number },
  anomalies: Anomaly[]
): Promise<void> {
  await ensureHistoryBranch(owner, repo);
  const { entries, sha } = await readHistoryFile(owner, repo, workflowId);

  const entry: DiagnosisSnapshot = {
    timestamp: new Date().toISOString(),
    runs_analyzed: stats.runs_analyzed,
    failure_rate_pct: stats.failure_rate_pct,
    avg_duration_min: stats.avg_duration_min,
    anomaly_types: anomalies.map((a) => a.type),
  };

  const updated = [entry, ...entries].slice(0, HISTORY_LIMIT);
  await writeHistoryFile(owner, repo, workflowId, updated, sha);
}

/** Retrieves past diagnosis snapshots for a workflow, most recent first. */
export async function getDiagnosisHistory(
  owner: string,
  repo: string,
  workflowId: number,
  limit = 20
): Promise<DiagnosisSnapshot[]> {
  const { entries } = await readHistoryFile(owner, repo, workflowId);
  return entries.slice(0, limit);
}

/**
 * Compares the current anomaly list against the most recent stored
 * snapshot (if any) to distinguish a brand-new problem from one that's
 * already been showing up in past diagnoses.
 */
export function diffAgainstPrevious(
  currentAnomalyTypes: string[],
  previous: DiagnosisSnapshot | null
): { newTypes: string[]; recurringTypes: string[] } {
  const prevTypes = new Set(previous?.anomaly_types ?? []);
  const newTypes = currentAnomalyTypes.filter((t) => !prevTypes.has(t));
  const recurringTypes = currentAnomalyTypes.filter((t) => prevTypes.has(t));
  return { newTypes, recurringTypes };
}
